spring:
  config:
    import: "configserver:http://localhost:8888"
    activate:
      on-profile: dev

logging:
  level:
    com.autodrive.authuser: DEBUG
    com.autodrive.common: DEBUG
    org.hibernate.SQL: DEBUG
